AM_LDFLAGS changes for osx/ppc
Remove "-nostartfiles" flag to avoid the following error:
ld: symbol dyld_stub_binding_helper not defined (usually in crt1.o/dylib1.o/bundle1.o)

Introduce other flags for dynamic-linking.