fix(msvc): put math.h after _USE_MATH_DEFINES again
The _USE_MATH_DEFINES is useless otherwise and MSVC does not know M_PI (error C2065: 'M_PI': undeclared identifier)